version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Hello from the other side
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 205481514190.dkr.ecr.us-east-1.amazonaws.com
      - echo Log in to ECR successfull
      - aws ecr batch-delete-image --repository-name app-helloworld --image-ids imageTag=${IMAGE_TAG}
  build:
    commands:
      - docker-compose --file=docker-compose.yml build
      - docker tag $IMAGE_NAME:latest 205481514190.dkr.ecr.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
      - docker push 205481514190.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest